# caffe
1. [dummy convolution](#dummy-conv-layer)
1. [dummy depthwise](#dummy-depthwise-layer)

In [1]:
import sys
sys.path.insert(0, "/home/allen/Documents/caffe/python")
import caffe
import numpy as np

In [45]:
from caffe import layers as L
from caffe import params as P

In [38]:
caffe_net = caffe.NetSpec()

In [40]:
caffe_net['data1'] = data1
caffe_net['data2'] = data2
caffe_net['data3'] = data3
caffe_net['eltwise'] = elt

In [41]:
caffe_net.to_proto()

layer {
  name: "data1"
  type: "Input"
  top: "data1"
  input_param {
    shape {
      dim: 1
      dim: 3
      dim: 112
      dim: 112
    }
  }
}
layer {
  name: "data2"
  type: "Input"
  top: "data2"
  input_param {
    shape {
      dim: 1
      dim: 3
      dim: 112
      dim: 112
    }
  }
}
layer {
  name: "data3"
  type: "Input"
  top: "data3"
  input_param {
    shape {
      dim: 1
      dim: 3
      dim: 112
      dim: 112
    }
  }
}
layer {
  name: "eltwise"
  type: "Eltwise"
  bottom: "data1"
  bottom: "data2"
  bottom: "data3"
  top: "eltwise"
  eltwise_param {
    operation: SUM
  }
}

In [35]:
data1 = L.Input(shape=dict(dim=[1,3,112,112]))
data2 = L.Input(shape=dict(dim=[1,3,112,112]))
data3 = L.Input(shape=dict(dim=[1,3,112,112]))
elt = L.Eltwise(data1, data2, data3, operation=P.Eltwise.SUM)

#### load model

In [23]:
deploy="/home/allen/mobilenet_multitask_20190322.temp.cp.prototxt"
caffe_model='/home/allen/mobilenet_multitask_20190322.temp.caffemodel'
net = caffe.Net(deploy,caffe_model,caffe.TEST)

#### preprocessing

In [24]:
_input = cv2.imread(path)
_input = cv2.resize(_input,(112,112))
_input = (_input/255.0 - 0.5)/0.5

caffe_input = np.transpose(_input, (2,0,1))[np.newaxis, :]

In [16]:
np.transpose(tf_input, (0,3,1,2))

array([[[[-0.45882353, -0.45882353, -0.46666667, ...,  0.00392157,
           0.01176471,  0.02745098],
         [-0.43529412, -0.44313725, -0.45098039, ...,  0.01176471,
           0.00392157,  0.01960784],
         [-0.42745098, -0.42745098, -0.43529412, ...,  0.00392157,
           0.01176471,  0.02745098],
         ...,
         [-0.45098039, -0.44313725, -0.49019608, ...,  0.30980392,
           0.30980392,  0.30980392],
         [-0.45882353, -0.45098039, -0.52156863, ...,  0.30196078,
           0.30196078,  0.30980392],
         [-0.51372549, -0.52941176, -0.61568627, ...,  0.30196078,
           0.30196078,  0.31764706]],

        [[-0.46666667, -0.45882353, -0.45098039, ...,  0.04313725,
           0.05098039,  0.06666667],
         [-0.44313725, -0.44313725, -0.43529412, ...,  0.05098039,
           0.04313725,  0.05882353],
         [-0.43529412, -0.42745098, -0.42745098, ...,  0.04313725,
           0.05098039,  0.06666667],
         ...,
         [-0.4745098 , -0.50588235

In [11]:
caffe_input

array([[[[-0.45882353, -0.45882353, -0.46666667, ...,  0.00392157,
           0.01176471,  0.02745098],
         [-0.43529412, -0.44313725, -0.45098039, ...,  0.01176471,
           0.00392157,  0.01960784],
         [-0.42745098, -0.42745098, -0.43529412, ...,  0.00392157,
           0.01176471,  0.02745098],
         ...,
         [-0.45098039, -0.44313725, -0.49019608, ...,  0.30980392,
           0.30980392,  0.30980392],
         [-0.45882353, -0.45098039, -0.52156863, ...,  0.30196078,
           0.30196078,  0.30980392],
         [-0.51372549, -0.52941176, -0.61568627, ...,  0.30196078,
           0.30196078,  0.31764706]],

        [[-0.46666667, -0.45882353, -0.45098039, ...,  0.04313725,
           0.05098039,  0.06666667],
         [-0.44313725, -0.44313725, -0.43529412, ...,  0.05098039,
           0.04313725,  0.05882353],
         [-0.43529412, -0.42745098, -0.42745098, ...,  0.04313725,
           0.05098039,  0.06666667],
         ...,
         [-0.4745098 , -0.50588235

#### forward

In [28]:
net.blobs['blob1'].data[...] = caffe_input
embedding = net.forward()

In [34]:
embedding['sigmoid_prob1']

array([[0.30726722]], dtype=float32)

array([[-2.0569167 ,  2.2177708 , -2.0151384 ,  1.9262052 , -1.7954506 ,
         1.7967215 , -1.5535408 ,  1.6716592 , -1.562477  ,  1.4859504 ,
        -1.293287  ,  1.5827228 , -1.2759242 ,  1.4708483 , -1.59766   ,
         1.1100159 , -1.2941504 ,  1.2946421 , -1.2329605 ,  1.3136355 ,
        -1.2851585 ,  1.218411  , -1.1929178 ,  1.2144083 , -1.3668921 ,
         0.8933704 , -0.88162947,  1.2286606 , -0.8739527 ,  0.9999685 ,
        -0.66567105,  0.80061245, -0.40747237,  0.7218433 , -0.34840328,
         0.44554165, -0.26410255,  0.26102898, -0.11449168,  0.13764828,
        -0.0280425 , -0.08047274,  0.1399315 , -0.14167714,  0.43023863,
        -0.02579966,  0.40510562, -0.30545947,  0.60345745, -0.46024734,
         0.75440496, -0.4886549 ,  0.82801884, -0.6817773 ,  0.7985397 ,
        -0.8874794 ,  0.92524827, -1.0285472 ,  1.1571255 , -1.0018244 ,
         1.0471345 , -1.3038747 ,  1.4094805 , -1.0448556 ,  1.327141  ,
        -1.2800848 ,  1.3011665 , -1.3201606 ,  1.3

In [41]:
a = net.blobs['fc_blob3'].data
b = net.blobs['sigmoid_prob1'].data

In [42]:
b

array([[0.30726722]], dtype=float32)

In [45]:
1.0 / (1 + math.exp(-a))

0.3072672078882084

In [12]:
caffe_output = net.blobs['334'].data
# normalized_out = out / np.linalg.norm(out)

In [13]:
trans_tf_output = np.transpose(tf_output, (0,3,1,2))

In [17]:
caffe_output[0,0,:,:]

NameError: name 'caffe_output' is not defined

In [23]:
np.flip(trans_tf_output)[0,0,:,:]

array([[-5.2734248e-02, -1.3860692e-01, -1.3460992e-01, ...,
         3.1584096e-01,  3.1197596e-01,  2.9990199e-01],
       [-2.0925051e-02, -1.0163886e-01, -9.4726495e-02, ...,
         2.8029236e-01,  2.4022545e-01,  1.9750033e-01],
       [-1.6264418e-02, -8.5879825e-02, -9.2555188e-02, ...,
         2.6499698e-01,  2.3532212e-01,  1.8790987e-01],
       ...,
       [-2.4213150e-04, -7.4104555e-03, -6.6696368e-03, ...,
         1.5966980e-01,  1.3823235e-01,  1.2317617e-01],
       [-8.5471844e-04, -2.8979240e-03,  7.8092641e-03, ...,
         1.3362150e-01,  1.3228619e-01,  1.2900597e-01],
       [ 1.1870424e-03,  2.6170681e-03,  2.8478617e-03, ...,
         1.3213433e-01,  1.3156262e-01,  1.3363789e-01]], dtype=float32)

In [20]:
caffe_output = embedding / np.linalg.norm(embedding)

In [39]:
normalized_tf_output = tf_output / np.linalg.norm(tf_output)

In [22]:
np.sum(caffe_output * normalized_tf_output)

0.9999999

In [84]:
paths = [os.path.join(root, f) for root, _, files in os.walk("/home/allen/Lennon_Lin/") for f in files if 'jpg' in f or  'png' in f]
embs = []
for path in paths:   

    _input = cv2.imread(path)
    _input = cv2.resize(_input,(112,112))
    _input = (_input/255.0 - 0.5)/0.5

    caffe_input = np.transpose(_input, (2,0,1))[np.newaxis, :]
    net.blobs['0'].data[...] = caffe_input
    embedding = net.forward()['477'].copy()
    embs.append(embedding)

normalized_embs = []
for i in embs:
    normalized_embs.append(i / np.linalg.norm(i))

normalized_embs_arr = np.array(normalized_embs).squeeze()

np.matmul(normalized_embs_arr, normalized_embs_arr.transpose())[0]

array([1.0000004 , 0.7134838 , 0.68740374, 0.63135636, 0.31626278,
       0.64604163, 0.3802653 , 0.4661587 , 0.35336965, 0.34694254,
       0.5389409 , 0.38242942, 0.40371138, 0.32311618, 0.15025601,
       0.3828416 , 0.26598275, 0.28421402, 0.52755284, 0.41375685],
      dtype=float32)

In [27]:
tflite_output = np.load("/home/allen/00140_embedding.npy")
tflite_output = tflite_output[np.newaxis, :]

In [31]:
normalized_tf_output

array([[ 0.03098539, -0.01920414, -0.06054536, -0.03239093, -0.03895952,
         0.04260923, -0.00063052,  0.06049987,  0.02268264,  0.02008231,
         0.03962162, -0.04164155, -0.02439435,  0.00142316, -0.0123225 ,
         0.03314535, -0.0577183 , -0.05079812, -0.02055868,  0.01013203,
        -0.00118758, -0.05671863, -0.0444616 , -0.01263302, -0.05209986,
        -0.02911533,  0.02838958,  0.00202656, -0.01508614,  0.04455404,
         0.03431712,  0.01210972, -0.00203951,  0.01067953,  0.03043412,
        -0.01058405, -0.00432229, -0.06245269,  0.01691664,  0.02557359,
        -0.01972048, -0.04603468,  0.03518996, -0.0583852 ,  0.02593375,
        -0.00249705,  0.00986063, -0.00028198, -0.02440025,  0.051347  ,
         0.01176422,  0.04838645,  0.01441191, -0.01849311,  0.02700114,
         0.02861025,  0.03077151,  0.05156572, -0.06263892, -0.00825037,
        -0.03154445,  0.03638807, -0.0037927 , -0.08963073, -0.02630693,
         0.00249512,  0.07729867,  0.0175095 , -0.0

In [41]:
np.sum(tflite_output * normalized_tf_output)

0.16432562

In [107]:
normalized_output

array([[-3.63282040e-02, -3.57723162e-02,  3.53021994e-02,
         8.10580328e-04, -3.38179618e-03,  1.73042193e-02,
         8.08609556e-03, -3.32332291e-02,  2.09442489e-02,
        -7.87368789e-02,  2.48556361e-02, -9.53205004e-02,
        -4.71324511e-02, -1.71131566e-02, -1.31104589e-02,
         5.53108705e-03,  1.43610490e-02,  7.43892603e-03,
        -2.95287035e-02,  6.29728660e-02,  5.90888076e-02,
         7.76419789e-03,  3.62838581e-02,  7.13380203e-02,
         4.20546941e-02,  2.34157983e-02,  9.25904438e-02,
         9.51686036e-03, -3.83009203e-02, -2.72125732e-02,
         1.83203910e-02, -9.57886106e-04, -5.98643795e-02,
        -3.83775681e-02,  6.37396192e-03, -6.34784698e-02,
         8.70735664e-03,  1.47271650e-02,  2.48763189e-02,
        -2.28058491e-02,  2.57522408e-02,  1.91656984e-02,
        -2.53685098e-02,  6.21827245e-02,  4.60363366e-02,
        -1.56486649e-02,  2.02384014e-02,  4.01177742e-02,
         7.94488713e-02,  7.32454583e-02, -5.61649501e-0

In [88]:
np.sum(normalized_output * normalized_out)

-0.00058991835

## dummy conv layer
[top](#caffe)

In [129]:
deploy="/home/allen.jc.lin/tf_testing/single_conv.prototxt"
net = caffe.Net(deploy,caffe.TRAIN)
net.params['334'][0].data[...] = np.ones((1,3,3,3))

### NHWC

In [130]:
tf_input[0,:,:,0].shape

(7, 7)

In [131]:
caffe_input = np.transpose(tf_input,(0,3,1,2))

### NCHW

In [88]:
tf_input[0,0,:,:].shape

(7, 3)

In [77]:
caffe_input = tf_input

In [132]:
net.blobs['0'].data[...] = caffe_input
caffe_output = net.forward()['334']

In [133]:
print(caffe_output[0,0,:,:].shape)
print(caffe_output[0,0,:,:])


(4, 4)
[[ 7.075458   9.458788   9.173692   6.019715 ]
 [ 9.410875  12.871306  12.739386  10.120045 ]
 [ 7.644647  11.824449  13.184648   7.5542674]
 [ 6.893902   9.88094    9.679523   5.1581664]]


In [134]:
print(tf_output[0,:,:,0].shape)
print(tf_output[0,:,:,0])
print(np.transpose(tf_output, (0,3,1,2))[0,0,:,:])

(4, 4)
[[ 7.075458   9.458788   9.173692   6.019715 ]
 [ 9.410875  12.871306  12.739386  10.120045 ]
 [ 7.644647  11.824449  13.184648   7.5542674]
 [ 6.893902   9.88094    9.679523   5.1581664]]
[[ 7.075458   9.458788   9.173692   6.019715 ]
 [ 9.410875  12.871306  12.739386  10.120045 ]
 [ 7.644647  11.824449  13.184648   7.5542674]
 [ 6.893902   9.88094    9.679523   5.1581664]]


In [106]:
np.flip(np.swapaxes(tf_output,3,2))[0,0,:,:] - caffe_output[0,0,:,:]

array([[-1.,  0.,  0., -1.,  0.,  0., -1., -1.,  0.,  0.],
       [-1.,  0.,  0., -2.,  0.,  0., -1., -1.,  0.,  0.],
       [-1.,  0.,  0., -2.,  0.,  0., -1., -1.,  0.,  0.],
       [ 0.,  2.,  2.,  0.,  2.,  2.,  1.,  1.,  2.,  2.],
       [-1.,  0.,  0., -2.,  0.,  0., -1., -1.,  0.,  0.],
       [-1.,  0.,  0., -2.,  0.,  0., -1., -1.,  0.,  0.],
       [ 0.,  1.,  1., -1.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  1., -1.,  1.,  1.,  0.,  0.,  1.,  1.],
       [-1.,  0.,  0., -2.,  0.,  0., -1., -1.,  0.,  0.],
       [ 0.,  2.,  2.,  0.,  2.,  2.,  1.,  1.,  2.,  2.]], dtype=float32)

## dummy depthwise layer  
[top](#caffe)

In [1]:
import sys
sys.path.insert(0, "/home/allen/Documents/caffe/python")
import caffe
import numpy as np

In [25]:
img1 = np.array([[[[1],[2],[3],[4]],[[2],[1],[3],[4]],[[3],[1],[2],[4]],[[4],[1],[2],[3]]]])
img2 = np.array([[[[1],[1],[1],[1]],[[1],[1],[1],[1]],[[1],[1],[1],[1]],[[1],[1],[1],[1]]]])
img = np.concatenate([img1,img2,img1],axis=3)
np.random.seed(5)
filter1 = np.random.rand(3,3,1,1)
filter2 = np.random.rand(3,3,1,1)
filter3 = np.random.rand(3,3,1,1)
kernel = np.concatenate((filter1,filter2,filter3),axis=2)
kernel = kernel.transpose(2,3,0,1)
img = img.transpose(0,3,1,2)

In [24]:
np.random.seed(5)
np.random.rand(3,3,1,1)

array([[[[0.22199317]],

        [[0.87073231]],

        [[0.20671916]]],


       [[[0.91861091]],

        [[0.48841119]],

        [[0.61174386]]],


       [[[0.76590786]],

        [[0.51841799]],

        [[0.2968005 ]]]])

In [28]:
kernel

array([[[[0.22199317, 0.87073231, 0.20671916],
         [0.91861091, 0.48841119, 0.61174386],
         [0.76590786, 0.51841799, 0.2968005 ]]],


       [[[0.18772123, 0.08074127, 0.7384403 ],
         [0.44130922, 0.15830987, 0.87993703],
         [0.27408646, 0.41423502, 0.29607993]]],


       [[[0.62878791, 0.57983781, 0.5999292 ],
         [0.26581912, 0.28468588, 0.25358821],
         [0.32756395, 0.1441643 , 0.16561286]]]])

In [33]:
kernel.transpose((2,3,0,1))

array([[[[0.22199317],
         [0.18772123],
         [0.62878791]],

        [[0.87073231],
         [0.08074127],
         [0.57983781]],

        [[0.20671916],
         [0.7384403 ],
         [0.5999292 ]]],


       [[[0.91861091],
         [0.44130922],
         [0.26581912]],

        [[0.48841119],
         [0.15830987],
         [0.28468588]],

        [[0.61174386],
         [0.87993703],
         [0.25358821]]],


       [[[0.76590786],
         [0.27408646],
         [0.32756395]],

        [[0.51841799],
         [0.41423502],
         [0.1441643 ]],

        [[0.2968005 ],
         [0.29607993],
         [0.16561286]]]])

In [23]:
deploy="/home/allen/20190220_fmobilenet_fc_align.prototxt"
net = caffe.Net(deploy,caffe.TRAIN)
# net.params['334'][0].data[...] = kernel

In [83]:
len(net.params['334'])

1

In [4]:
network = {}
for i, layer in enumerate(net._layer_names):
    bottoms = net.bottom_names[layer]
    tops = net.top_names[layer]
    network[layer] = {}
    network[layer]['bottom'] = bottoms
    network[layer]['top'] = tops
    network[layer]['weights'] = []
    msg = "layer-{}:{:20}, type:{}\n ".format(i, layer, net.layers[i].type)
    msg += "-------------"
    if layer in net.params:
        for param in net.params[layer]:
            msg += "     weight:{}".format(param.data[...].shape)
            network[layer]['weights'].append(param.data[...])
    msg += "\n     from: "
    for bottom in bottoms:
        msg += "{:20} ".format(bottom)
    msg += "\n     to  : "
    for top in tops:
        msg += "{:20} ".format(top)
    msg += "\n------------- \n"
    print(msg)

layer-0:0                   , type:Input
 -------------
     from: 
     to  : 0                    
------------- 

layer-1:334                 , type:Convolution
 -------------     weight:(64, 3, 3, 3)
     from: 0                    
     to  : 334                  
------------- 

layer-2:335_bn              , type:BatchNorm
 -------------     weight:(64,)     weight:(64,)     weight:(1,)
     from: 334                  
     to  : 335                  
------------- 

layer-3:335                 , type:Scale
 -------------     weight:(64,)     weight:(64,)
     from: 335                  
     to  : 335                  
------------- 

layer-4:336_prelu           , type:PReLU
 -------------     weight:(64,)
     from: 335                  
     to  : 336                  
------------- 

layer-5:337                 , type:Convolution
 -------------     weight:(64, 1, 3, 3)
     from: 336                  
     to  : 337                  
------------- 

layer-6:338_bn            

In [3]:
import caffe.proto.caffe_pb2 as caffepb
net_params = caffepb.NetParameter()
f = open(deploy, 'rb')
net_str = f.read()
# net_params.ParseFromString(f.read())
# f.close()

In [4]:
from google.protobuf import text_format

In [5]:
text_format.Merge(net_str, net_params)

layer {
  name: "0"
  type: "Input"
  top: "0"
  input_param {
    shape {
      dim: 1
      dim: 3
      dim: 112
      dim: 112
    }
  }
}
layer {
  name: "334"
  type: "Convolution"
  bottom: "0"
  top: "334"
  convolution_param {
    num_output: 64
    bias_term: false
    group: 1
    pad_h: 1
    pad_w: 1
    kernel_h: 3
    kernel_w: 3
    stride_h: 2
    stride_w: 2
    dilation: 1
  }
}
layer {
  name: "335_bn"
  type: "BatchNorm"
  bottom: "334"
  top: "335"
  batch_norm_param {
    use_global_stats: true
    eps: 9.999999747378752e-06
  }
}
layer {
  name: "335"
  type: "Scale"
  bottom: "335"
  top: "335"
  scale_param {
    bias_term: true
  }
}
layer {
  name: "336_prelu"
  type: "PReLU"
  bottom: "335"
  top: "336"
}
layer {
  name: "337"
  type: "Convolution"
  bottom: "336"
  top: "337"
  convolution_param {
    num_output: 64
    bias_term: false
    group: 64
    pad_h: 1
    pad_w: 1
    kernel_h: 3
    kernel_w: 3
    stride_h: 1
    stride_w: 1
    dilation: 1
 

In [12]:
for layer in net_params.layer:
    print(layer.name)

0
334
335_bn
335
336_prelu
337
338_bn
338
339_prelu
340
341_bn
341
342_prelu
343
344_bn
344
345_prelu
346
347_bn
347
348
349_bn
349
350_prelu
351
352_bn
352
353_prelu
354
355_bn
355
356
357
358_bn
358
359_prelu
360
361_bn
361
362_prelu
363
364_bn
364
365
366
367_bn
367
368_prelu
369
370_bn
370
371_prelu
372
373_bn
373
374
375
376_bn
376
377_prelu
378
379_bn
379
380_prelu
381
382_bn
382
383
384
385_bn
385
386_prelu
387
388_bn
388
389_prelu
390
391_bn
391
392
393_bn
393
394_prelu
395
396_bn
396
397_prelu
398
399_bn
399
400
401
402_bn
402
403_prelu
404
405_bn
405
406_prelu
407
408_bn
408
409
410
411_bn
411
412_prelu
413
414_bn
414
415_prelu
416
417_bn
417
418
419
420_bn
420
421_prelu
422
423_bn
423
424_prelu
425
426_bn
426
427
428
429_bn
429
430_prelu
431
432_bn
432
433_prelu
434
435_bn
435
436
437
438_bn
438
439_prelu
440
441_bn
441
442_prelu
443
444_bn
444
445
446
447_bn
447
448_prelu
449
450_bn
450
451_prelu
452
453_bn
453
454
455_bn
455
456_prelu
457
458_bn
458
459_prelu
460
461_bn
46

In [25]:
network = {}
for layer in net_params.layer:
    bottoms = layer.bottom
    tops = layer.top
    network[layer.name] = {}
    network[layer.name]['config'] = layer
    network[layer.name]['weights'] = []
    
    msg = "{:20}, type:{}\n ".format(layer.name, layer.type)
    msg += "-------------"
    if layer.name in net.params:
        for param in net.params[layer.name]:
            msg += "     weight:{}".format(param.data[...].shape)
            network[layer.name]['weights'].append(param.data[...])
    msg += "\n     from: "
    for bottom in bottoms:
        msg += "{:20} ".format(bottom)
    msg += "\n     to  : "
    for top in tops:
        msg += "{:20} ".format(top)
    msg += "\n------------- \n"
    print(msg)

0                   , type:Input
 -------------
     from: 
     to  : 0                    
------------- 

334                 , type:Convolution
 -------------     weight:(64, 3, 3, 3)
     from: 0                    
     to  : 334                  
------------- 

335_bn              , type:BatchNorm
 -------------     weight:(64,)     weight:(64,)     weight:(1,)
     from: 334                  
     to  : 335                  
------------- 

335                 , type:Scale
 -------------     weight:(64,)     weight:(64,)
     from: 335                  
     to  : 335                  
------------- 

336_prelu           , type:PReLU
 -------------     weight:(64,)
     from: 335                  
     to  : 336                  
------------- 

337                 , type:Convolution
 -------------     weight:(64, 1, 3, 3)
     from: 336                  
     to  : 337                  
------------- 

338_bn              , type:BatchNorm
 -------------     weight:(64,)     w

name: "0"
type: "Input"
top: "0"
input_param {
  shape {
    dim: 1
    dim: 3
    dim: 112
    dim: 112
  }
}

In [7]:
f.readlines()[0]

b'layer {\n'

In [57]:
net.top_names['334']

['334']

In [75]:
len(net.layers)

207

In [73]:
dir(net.layers)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__instance_size__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'append',
 'extend']

In [31]:
net.blobs['0'].data[...] = img
caffe_output = net.forward()['334']

In [32]:
caffe_output

array([[[[ 3.0455356 ,  6.6713    ,  9.257795  ,  9.0808735 ],
         [ 4.7247915 , 10.154223  , 11.703827  , 12.463874  ],
         [ 6.3956337 , 10.578259  , 10.696621  , 11.026845  ],
         [ 5.384305  ,  7.3364925 ,  6.520999  ,  7.229371  ]],

        [[ 1.7485619 ,  2.4639575 ,  2.4639575 ,  1.2879406 ],
         [ 2.5677435 ,  3.4708602 ,  3.4708602 ,  1.556403  ],
         [ 2.5677435 ,  3.4708602 ,  3.4708602 ,  1.556403  ],
         [ 1.8574286 ,  2.4864588 ,  2.4864588 ,  0.86808157]],

        [[ 1.2458037 ,  2.8920863 ,  3.8225572 ,  3.4955497 ],
         [ 3.200762  ,  6.6234217 ,  8.80938   ,  7.373701  ],
         [ 3.6095207 ,  7.0121665 ,  7.730293  ,  6.9637175 ],
         [ 3.7317743 ,  5.521199  ,  5.784136  ,  4.962623  ]]]],
      dtype=float32)