# practice

### torch

In [2]:
import sys
sys.path.insert(0, '/media/allen/mass/deep-learning-works/')
import os
import os.path as osp
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F

import cv2
from PIL import Image 

def to_pil(cv_img):
    img = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
    return Image.fromarray(img)


In [6]:
a = torch.rand(1,3,4,4)
model = nn.ConvTranspose2d(3,3, kernel_size=4, stride=2, padding=1)

In [1]:
import os

In [22]:
n_folders = len([f for f in os.scandir("../result/cifar10/") if f.is_dir()])

In [3]:
from src.factory.config_factory import _C as cfg, build_output

In [4]:
os.chdir("../")

In [5]:
build_output(cfg)

In [24]:
for f in os.scandir("../result/cifar10/"):
    print(f.path)

../result/cifar10/[OSNet]_[cifar10]_[augmix_ce]_[SGDW_nesterov]_[cosine_0.02_noRestart]_[scratch]
../result/cifar10/[OSNet]_[cifar10]_[augmix_aux_ce_]_[SGDW_nesterov]_[cosine_0.02_noRestart]_[scratch]
../result/cifar10/[OSNet]_[cifar10]_[augmix_ce]_[SGDW_nesterov]_[cosine_tune_result]_[scratch]
../result/cifar10/[OSNet]_[cifar10]_[augmix_ce]_[SGDW]_[cosine_lr_0.1_period_15]_[resume_0.9436]
../result/cifar10/[OSNet]_[cifar10]_[ce]_[SGD]_[cosine_lr_0.2]_[scratch]
../result/cifar10/[OSNet]_[cifar10]_[augmix_ce]_[SGD]_[cosine_lr_0.1_period_15]_[scratch]
../result/cifar10/[OSNet]_[cifar10]_[augmix_ce]_[SGD]_[cosine_lr_0.1]_[scratch]
../result/cifar10/[OSNet]_[cifar10]_[augmix_ce]_[SGD]_[cosine_lr_0.0001]_[resume_0.94]
../result/cifar10/[OSNet]_[cifar10]_[ce]_[SGD]_[cosine_lr_0.1]_[scratch]
../result/cifar10/[ResNet]_[cifar10]_[ce]_[SGD]_[cosine_lr_0.1]_[scratch]


In [2]:
model = nn.BatchNorm2d(2)

In [3]:
a = torch.rand(1,2,2,2)

In [23]:
model.train()
model(a)
print(model.running_mean)
print(model.running_var)

tensor([0.4240, 0.3544])
tensor([0.3137, 0.2147])


In [24]:
model.state_dict()

OrderedDict([('weight', tensor([1., 1.])),
             ('bias', tensor([0., 0.])),
             ('running_mean', tensor([0.4240, 0.3544])),
             ('running_var', tensor([0.3137, 0.2147])),
             ('num_batches_tracked', tensor(15))])

In [27]:
model.eval()
print(model.running_mean)
print(model.running_var)

tensor([0.4240, 0.3544])
tensor([0.3137, 0.2147])


In [28]:
model.state_dict()

OrderedDict([('weight', tensor([1., 1.])),
             ('bias', tensor([0., 0.])),
             ('running_mean', tensor([0.4240, 0.3544])),
             ('running_var', tensor([0.3137, 0.2147])),
             ('num_batches_tracked', tensor(15))])